name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run lint
