name: Release new version

on:
  workflow_dispatch:

jobs:
  release:
    uses: mendabot/actions/.github/workflows/release.yml@32015b2383ed7504c8e0e99682e266b122564819 # main
    secrets:
      signing-key: ${{ secrets.MENDABOT_SIGNING_KEY }}
      git-token: ${{ secrets.MENDABOT_WRITE_ACCESS_GIT_TOKEN }}
